### ISSUE TITLE
Cannot execute the tool from terminal without prefixing `node` keyword

### ISSUE THREAD

**Issue by SerpentBytes** [cychu42/staticSiteCon#1]
## Environment Information

Operation System: macOS Monterey
Node version: v16.17.0

## Bug Description

To run the SSG tool from the terminal, I have to prefix `staticSiteCon -h` with the `node` keyword. The terminal throws an error if I try to run the tool without adding  `node` first.

See below:

<img width="569" alt="issue1" src="https://user-images.githubusercontent.com/50856799/190255257-a8329e03-96c3-4615-96db-46299ca13029.png">

## Expected Behaviour

I would expect to run the tool without having to use the `node` keyword. 

## To Reproduce:
1. `cd` into the project directory
2. Run `staticSiteCon -h`

**Comment by humphd** [comment]
A couple things:

- to run a binary in the current directory, you'd need to use `./staticSiteCon`, since your current directory is not in your path (i.e., it won't look in the current directory for that file unless you tell it that you want it to)
- to run a node program like this, you need to add a shebang, see https://stackoverflow.com/questions/20638520/appropriate-hashbang-for-node-js-scripts
- the file would need to be executable

See https://medium.com/netscape/a-guide-to-create-a-nodejs-command-line-package-c2166ad0452e for some more ideas.

For 0.1, running it with `node ...` all the time is fine.  This could be something you fix in subsequent releases.

Nice issue, @SerpentBytes.

**Comment by cychu42** [comment]
Thank you both for all the information. This idea didn't occur to me at the time.
I'll consider doing so in a future release. For now, I'm going to close this issue as it as.

**Comment by humphd** [comment]
NOTE: a good use of Issues is to leave them open as planning documents, where you collect use cases, information, and give progress updates.  Let's say you wanted to do this in a future release, you could use this issue to schedule the work.

**Comment by cychu42** [comment]
I see. I thought we are supposed to close any open issue for lab 1.
I'll leave this as open then.

**Comment by humphd** [comment]
Understood.  No, you can leave open any issues you want to follow-up on later.
